FROM debian:jessie
MAINTAINER brucepcarvalho@gmail.com

# persistent / runtime deps
RUN apt-get update && apt-get install -y ca-certificates curl libpcre3 librecode0 libsqlite3-0 libxml2 --no-install-recommends && rm -r /var/lib/apt/lists/*

# phpize deps
RUN apt-get update && apt-get install -y autoconf file g++ gcc libc-dev make pkg-config re2c --no-install-recommends && rm -r /var/lib/apt/lists/*

ENV PHP_INI_DIR /usr/local/etc/php
RUN mkdir -p $PHP_INI_DIR/conf.d

##<autogenerated>##
ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
##</autogenerated>##

ENV GPG_KEYS 0BD78B5F97500D450838F95DFE857D9A90D90EC1 0B96609E270F565C13292B24C13C70B87267B52D
RUN set -xe \
   && for key in $GPG_KEYS; do \
      gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
   done

ENV PHP_VERSION 5.5.27
ENV XDEBUG_VERSION XDEBUG_2_3_3

# --enable-mysqlnd is included below because it's harder to compile after the fact the extensions are (since it's a plugin for several extensions, not an extension in itself)
RUN buildDeps=" \
      $PHP_EXTRA_BUILD_DEPS \
      libcurl4-openssl-dev \
      libpcre3-dev \
      libreadline6-dev \
      librecode-dev \
      libffi-dev \
      libglib2.0-dev \
      libjpeg-dev \
      libpng-dev \
      libmcrypt-dev \
      libtiff-dev \
      libgif-dev \
      libsqlite3-dev \
      libmagickcore-dev \
      libmagickwand-dev \
      libssl-dev \
      libxml2-dev \
      xz-utils \
   " \
   && set -x \
   && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
   && curl -SL "http://php.net/get/php-$PHP_VERSION.tar.xz/from/this/mirror" -o php.tar.xz \
   && curl -SL "http://php.net/get/php-$PHP_VERSION.tar.xz.asc/from/this/mirror" -o php.tar.xz.asc \
   && gpg --verify php.tar.xz.asc \
   && mkdir -p /usr/src/php \
   && tar -xof php.tar.xz -C /usr/src/php --strip-components=1 \
   && rm php.tar.xz* \
   && cd /usr/src/php \
   && ./configure \
      --with-config-file-path="$PHP_INI_DIR" \
      --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
      $PHP_EXTRA_CONFIGURE_ARGS \
      --disable-cgi \
      --enable-mysqlnd \
      --enable-exif \
      --with-jpeg-dir \
      --with-gd \
      --with-freetype-dir \
      --with-openssl \
      --with-curl \
      --with-openssl \
      --with-pcre \
      --with-readline \
      --with-recode \
      --with-zlib \
      --enable-zip \
   && make -j"$(nproc)" \
   && make install \
   && { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
   && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps \
   && make clean

RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/America/Manaus /etc/localtime
RUN "date"
RUN ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so.6.10.1 /usr/lib/libfreetype.so.6

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
   imagemagick \
   graphicsmagick \
   libfreetype6-dev \
   libjpeg62-turbo-dev \
   libpng12-dev \
   libbz2-dev \
   php-pear \
   curl \
   git \
  && rm -r /var/lib/apt/lists/*

COPY docker-php-ext-* /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-php-ext-*

RUN docker-php-ext-install zip bz2 mbstring json \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install gd
# opcache
RUN docker-php-ext-install opcache

# mcrypt
RUN runtimeRequirements="re2c libmcrypt-dev" \
   && apt-get update && apt-get install -y ${runtimeRequirements} \
   && docker-php-ext-install mcrypt \
   && rm -rf /var/lib/apt/lists/*

# yaml
RUN buildRequirements="libyaml-dev" \
   && apt-get update && apt-get install -y ${buildRequirements} \
   && pecl install yaml \
   && echo "extension=yaml.so" > /usr/local/etc/php/conf.d/ext-yaml.ini \
   && apt-get purge -y ${buildRequirements} \
   && rm -rf /var/lib/apt/lists/*

# imagick
RUN runtimeRequirements="libmagickwand-6.q16-dev --no-install-recommends" \
   && apt-get update && apt-get install -y ${runtimeRequirements} \
   && ln -s /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/MagickWand-config /usr/bin/ \
   && pecl install imagick \
   && echo "extension=imagick.so" > /usr/local/etc/php/conf.d/ext-imagick.ini \
   && rm -rf /var/lib/apt/lists/*

WORKDIR /root

RUN git clone -b $XDEBUG_VERSION --single-branch --depth 1 https://github.com/xdebug/xdebug.git \
   && cd xdebug \
   && phpize \
   && ./configure --enable-xdebug \
   && make \
   && make install \
   && cd ../ && rm -r xdebug

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin \
   && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

RUN apt-get update -qq && apt-get install -y locales -qq && locale-gen pt_BR.UTF-8 pt_br && dpkg-reconfigure locales && dpkg-reconfigure locales && locale-gen C.UTF-8 && /usr/sbin/update-locale LANG=C.UTF-8
RUN rm -rf /var/lib/apt/lists/*
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

RUN mkdir /var/log/phpfpm
ADD conf/php-fpm.conf /usr/local/etc/php-fpm.conf
ADD conf/php.ini /usr/local/etc/php/conf.d/php.ini
RUN usermod -u 1000 www-data
##<autogenerated>##
VOLUME ["/var/www"]
WORKDIR /var/www

EXPOSE 9000

CMD ["php-fpm"]
